const Types = {
    GET_DATA: 'GET_DATA',
    FAILED_GET_DATA: 'FAILED_GET_DATA',
    COMPLETE_GET_DATA: 'COMPLETE_GET_DATA',

    ADD_RECIPE_LOADING: 'ADD_RECIPE_LOADING',
    ADD_RECIPE: 'ADD_RECIPE',
    ADD_RECIPE_COMPLETE: 'ADD_RECIPE_COMPLETE',
    ADD_RECIPE_FAILED: 'ADD_RECIPE_FAILED',
    SET_LOADING: 'SET_LOADING',

    SEARCH: 'SEARCH',
    RESET_SEARCH: 'RESET_SEARCH',

    SIGN_IN_COMPLETE: 'SIGN_IN_COMPLETE',
    SIGN_IN_FAILED: 'SIGN_IN_FAILED',
    SET_LOADING_ADD_SIGN_IN: 'SET_LOADING_ADD_SIGN_IN',

    SET_LOADING_ADD_FAVE_RECIPE: 'SET_LOADING_ADD_FAVE_RECIPE',
    ADD_FAVE_RECIPE: 'ADD_FAVE_RECIPE',
    ADD_FAVE_RECIPE_COMPLETED: 'ADD_FAVE_RECIPE_COMPLETED',
    ADD_FAVE_RECIPE_FAILED: 'ADD_FAVE_RECIPE_FAILED',

    SET_LOADING_REMOVE_FAVE_RECIPE: 'SET_LOADING_REMOVE_FAVE_RECIPE',
    REMOVE_FAVE_RECIPE: 'REMOVE_FAVE_RECIPE',
    REMOVE_FAVE_RECIPE_COMPLETED: 'REMOVE_FAVE_RECIPE_COMPLETED',
    REMOVE_FAVE_RECIPE_FAILED: 'REMOVE_FAVE_RECIPE_FAILED'

}

export default Types;